### ISSUE TITLE
执行「$ fis3 init laravel」出错

### ISSUE THREAD

**Issue by zswang** [fis-scaffold/laravel#3]
![image](https://cloud.githubusercontent.com/assets/536587/10503160/ee9d7ce0-7325-11e5-9ec4-976f042ea952.png)

系统环境 Windows 7(64 位)
开发环境如图

详细错误信息：

``` bash
$ fis3 init laravel

 [INFO] Currently running fis3 (.\AppData\Roaming\npm\node_modules\fis3\)

 [INFO] Dir: D:\git
.\AppData\Roaming\npm\node_modules\fis3\node_modules\fis3-command-init\lib\tick.js                                                        :22
        this.stream.clearLine();
                    ^

TypeError: this.stream.clearLine is not a function
    at SimpleTick.render (.\AppData\Roaming\npm\node_modules\fis3\node_modules\fis                                                        3-command-init\lib\tick.js:22:21)
    at SimpleTick.tick (.\AppData\Roaming\npm\node_modules\fis3\node_modules\fis3-                                                        command-init\lib\tick.js:35:10)
    at new SimpleTick (.\AppData\Roaming\npm\node_modules\fis3\node_modules\fis3-c                                                        ommand-init\lib\tick.js:12:10)
    at progress (.\AppData\Roaming\npm\node_modules\fis3\node_modules\fis3-command                                                        -init\index.js:88:26)
    at ClientRequest.<anonymous> (.\AppData\Roaming\npm\node_modules\fis3\node_mod                                                        ules\fis3-command-init\node_modules\fis-scaffold-kernel\lib\util.js:227:21)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by zswang** [comment]
把这两函数调用屏蔽就可以执行了。

`..\fis3-command-init\lib\tick.js`

``` js
SimpleTick.prototype.render = function() {
    var len = this.tokens.length;
    var str = this.prefix + this.tokens[this.count%len] + ' ';

    if (str !== this.lastDraw) {
        // this.stream.clearLine();
        // this.stream.cursorTo(0);
        this.stream.write(str);
        this.lastDraw = str;
    }
};
```

**Comment by 2betop** [comment]
好的，收到！

**Comment by 2betop** [comment]
fixed: https://github.com/fex-team/fis3-command-init/commit/5d182b2f2fe82d8a2e8f58971343e0f903589686
